development:
  # secret_key_base: here_goes_my_secret_key_base
  google_client_id: "938174431673-iidiaeh0putgn7mfh41jgd2u2ngike6k.apps.googleusercontent.com"
  google_client_secret: "-2wA_Zs2KiYU0RZxRtDxOygd"
